name: Elixir CI

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

jobs:
  credo:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Elixir
        uses: erlef/setup-beam@v1
        with:
          elixir-version: '1.14.0' # or any version you need
          otp-version: '25.0'      # or any version you need

      - name: Install dependencies
        run: mix deps.get

      - name: Run credo
        run: mix credo --strict
