name: reviewdog
on: [pull_request, push]
jobs:
  credo:
    name: runner / credo
    runs-on: ubuntu-latest
    steps:
      - name: Check out code.
        uses: actions/checkout@v3
      - uses: erlef/setup-beam@v1
        with:
          otp-version: 26.2.5
          elixir-version: 1.16-otp-26
      - name: Install Dependencies
        run: |
          mix local.rebar --force
          mix local.hex --force
          mix deps.get
      - name: credo
        uses: ./
        with:
          github_token: ${{ secrets.github_token }}
