name: Credo
on: [pull_request, push]
jobs:
  credo:
    name: runner / credo
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Dependencies
        run: |
          mix local.rebar --force
          mix local.hex --force
          mix deps.get
      - run: mix credo diff --from-git-merge-base origin/master
